import mongoose from 'mongoose';

const packageSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  title: { 
    type: String, 
    required: true 
  }, // e.g., "Amazon Sneakers"
  
  description: { 
    type: String 
  },
  
  // The image uploaded by the customer (or admin)
  packageImage: {
    url: { type: String, required: true },
    public_id: { type: String, required: true }
  },

  // Tracking Info
  trackingNumber: { 
    type: String, 
    unique: true, 
    required: true 
  }, // Generated by SkyRush
  
  externalTracking: { 
    type: String 
  }, // Provided by Vendor (e.g., UPS/FedEx incoming)
  
  status: {
    type: String,
    enum: ['Pending', 'Received at Warehouse', 'Processing', 'In Transit', 'Delivered', 'On Hold'],
    default: 'Pending'
  },

  // Detailed tracking history for the timeline UI
  history: [
    {
      status: String,
      location: String,
      timestamp: { type: Date, default: Date.now },
      note: String
    }
  ],

  createdAt: { 
    type: Date, 
    default: Date.now 
  }
});

export const Package = mongoose.model('Package', packageSchema);